### ISSUE TITLE
error: Database migration failed.

### ISSUE THREAD

**Issue by mortezae** [buildlucid/lucid-cms#13]
No matter which db adapter I use, error is the same.

```js
export default lucid.config({
  db: new SQLiteAdapter({
    database: async () => new Database('db.sqlite'),
  }),

  /*
  db: new LibSQLAdapter({
    url: "libsql://db1-mortezae.turso.io",
    authToken:     process.env.TURSO_AUTH_TOKEN,
  }),
  */

  /*
  db: new PostgresAdapter({
    url: process.env.DATABASE_URL,
  }),
  */
}
```

lucid version:  0.5.0-alpha.1
node version: v20.14.0

**Comment by WillYallop** [comment]
Do you mind sharing some more information or a link to your repo if you have one so I can take a look please.

I created a fresh JS project yesterday using the SQLite adapter and didn't run into any issues with it and so I wonder if something else is going on.

**Comment by mortezae** [comment]
[This](https://github.com/mortezae/lucid-test) is my code.
Thanks for your attention.

**Comment by WillYallop** [comment]
Thanks for the link. Just had a look and I spot a couple things.

For the SQLite adapter to work it requires a [better-squite3](https://www.npmjs.com/package/better-sqlite3) DB instance passed to it. Currently you're constructing `Database`, but this isn't being imported from anywhere. I notice this is missing from the documentation site and so will get that updated to make it clearer.

As for the other database adapters the connection URLs you have defined for them in your `.env` file still include placeholder values.

**Comment by mortezae** [comment]
I should have noticed about Database isn't declared in the context. I imported It and migration done successfully using SQLite.
But regarding Postgres, It still doesn't work for me. I tested it with some online pg services but I see the same error. And the placeholders you mentioned are by intention.

**Comment by WillYallop** [comment]
I'm away for the week so won't be able to look into the Postgres adapter. Though getting that working isn't the priority at the moment and so it may be a while before I get to it.

**Comment by WillYallop** [comment]
Closed this as the initial problem is complete. I have made a note about the Postgres adapter and will look into it at a later date.

**Comment by WillYallop** [comment]
I've had a closer look now that i'm back from holiday and see the reason why your were getting a migration failed error with the `PostgresAdapter`. It's because you're trying to use a connection string as the url. Instead it should look like the bellow for instance.

```
db: new PostgresAdapter({
    connectionString: process.env.DATABASE_URL,
}),
```

These adapters are just abstractions on top of [Kysely's](https://kysely.dev/docs/dialects) dialects with the `PostgresAdapter` one specifically, requiring `PoolConfig` from the [pg](https://www.npmjs.com/package/pg) library.

As for the `LibSQLAdapter` the config you have seems correct to me, and i've just tested it and not running into any migration errors so I'm not sure what to suggest there at the moment. Though this is still a WIP and will be undergoing more testing down the line so hopefully that will address your issue.

There are a few other issues with the `PostgresAdapter` and `LibSQLAdapter` that I'm currently aware of however, so id recommend just using the `SQLiteAdapter` for now.

**Comment by mortezae** [comment]
Hi, I just saw it. Thanks for your follow up. I found this project to be a lighter and more minimal alternative to strapi etc. Even if it's young, It uses good tools and patterns and seem to have a big future, so I like to follow and learn. Anyway I'm new to Headless CMS so for now I don't use any for publishing/production and just sticked to my home crafted code.
